.TH e2fsimage 3 "14 January 2004" "0.0.1" 
.SH NAME
e2fsimage \- create and populate an ext2 filesystem image as non-root user
.SH SYNOPSIS
.B e2fsimage
[
.I -o image
] [
.I dir
] [
.I -r rootdir
] [
.I -d devices.txt
]
.SH DESCRIPTION
.LP
create an ext2 filesystem by copying the files from 
.I rootdir 
to 
.I image

.LP
The usual way to create ext2 filesystem images for initial ramdisks,
boot-floppys or bootable CDs were created by 

.LP
