.TH e2fsimage 1 "_DATE_" "_VERSION_" 
.SH NAME
e2fsimage \- create and populate an ext2 filesystem image as non-root user
.SH SYNOPSIS
.B e2fsimage
[
.I -f imgfile
] [
.I -d rootdir
] [
.I -u uid
] [
.I -g gid
] [
.I -s size
] [
.I -D file
] [
.I -p
] [
.I -v
] [
.I -n
]
.SH DESCRIPTION
.LP
.B e2fsimage
creates an ext2 filesystem by recursively copying the files from 
the existing directory structure
.I rootdir
.
.br
Supported filetypes are: regular files, directorys, hard-links
, soft-links, block special devices and character special devices 
and of course hidden files.
Hard links are resolved to result in hard links in the image.
Softlinks are copied as they are and not resolved or altered. In the 
.I rootdir
/home/user/build/rootdir a link to the file "file" should link to "->/file"
if the image is used as root filesystem or to "->file if used elsewhere
but not to "->/home/user/build/rootdir/file" since this
will most likely result into a broken link.

.LP
The usual way to create ext2 filesystem images for initial ramdisks,
boot-floppys or bootable CDs is to create an image with eg. 
.LP
.TS
tab (@);
l l.
1@ dd if=/dev/zero of=e2img bs=1024 count=4096
2@ mke2fs -F e2img
3@ mount -o loop e2img mounpoint
4@ cp -r rootdir/* mountpoint
.TE
.LP
At least the last command must be executed as root.
In order to set the different ownerships (usually root) and to create
the special device files root permissions are also needed.
.LP
Since all this results in a file that may belong to an 
ordinary user, this file can be created and filled with the fs
structure by her. This application manages to
create such an image as ordinary user without
.I sudo
or 
.I suid root
bit set. 
Of course suid-root programs in the filesystem image are possible 
by making them suid-user.
When this files are copied, the user is set to root and there you
have your suid-root program.  

.SH OPTIONS

.TP
.BI \-d\  rootdir
The content of the filesystemimage as a recursive copy of 
.I rootdir
. All files are copied while preserving all attributes but the uid/gid.
They will usually be set to 
.I root.root
This can be overwritten with the 
.B -u 
and 
.B -g
option respectively

.TP
.BI \-D\  devicefile
The devicefile does contain all special devices to be created, see
.I DEVICES
.br
. The default filename is 
.B .DEVICES

.TP
.BI \-f\  imgfile
This is the target file for the filesystem image. An existing file will be overwritten as long as 
.B \-n
is not given. The filesystem will be 
.I size
kilo bytes large.

.TP
.BI \-g\  gid
Change the default group-id from 0 to
.I gid
Until now there is only 1 gid for all files supported.

.TP
.BI \-n
This option allows to reuse an existing filesystem image defined by
.B \-f
The existing content is not modified by any means but there
may not exist a file with the same name as a newly created one.

.TP
.BI \-p
Preserve original file owner. If this option is omitted all files in the 
image will belong to root.

.TP
.BI \-s\  size
When the filesystem is created the size will be 4096 Kbytes or
.I size
Kbytes if this parameter is added.

.TP
.BI \-u\  uid
Change the default user-id from 0 to
.I uid
Until now there is only 1 uid for all files supported.

.TP
.BI \-v
Be more verbose.

.SH DEVICES
.LP
Usually the devices are created using
.B mknod
by root. Obviously this would absurd the existence of 
.B e2fsimage
to be a non-root tool. A device special file called
.B .DEVICES
can be placed in every directory (usually 
.I dev
) that will contain device special files. The format of this file is:
.LP
.I <name> <type> <major> <minor> <mode>
.TP
.BI name
the name of the file like 
.I ttyS0
.TP
.BI type 
Actually supported are
.I c
for character special devices and
.I b
for block special devices
.TP
.BI major\ minor 
This are the major and minor numbers of the device
.TP
.BI mode
The access mode for the file like 0644
.LP
A call to mknod like 
.B mknod -m 0600 ttyS1 4 65
would result in a line in
.B dev/.DEVICES 
as "ttyS1 4 65 0600"

.SH BUGS
.LP
I'm shure there are still enough bugs and enhancement possibilitys
since this is an alpha version.

.SH SEE ALSO
.B mkcramfs(8) mke2fs(8)

.SH AUTHOR
.LP
This program was written by 
.br
Christian Hohnstaedt <christian@hohnstaedt.de>
.br
The project homepage is http://www.hohnstaedt.de/e2fsimage
